{{- with .Values.route }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
  labels:
    {{- include "springboot-template.labels" $ | nindent 4 }}
  name: ${{values.component_id}}
spec:
  {{- if .host }}
  host: {{ .host }}
  {{- end }}
  {{- if .path }}
  path: {{ .path }}
  {{- end }}
  port:
    targetPort: {{ $.Values.service.port }}-tcp
  to:
    kind: Service
    name: ${{values.component_id}}-web
  wildcardPolicy: None
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
{{- end }}
